# Generated by Django 3.0.6 on 2020-05-15 11:02

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20170619_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_metadata',
            field=jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
