# Generated by Django 3.0.3 on 2020-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
    ]
