# Generated by Django 3.0.3 on 2020-03-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='uploads/', width_field=400),
        ),
    ]
