# Generated by Django 3.0.4 on 2020-04-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
    ]
