# Generated by Django 3.0.7 on 2020-06-06 05:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drive_data.Item')),
                ('file_file', models.FileField(default=None, upload_to='uploads/')),
                ('file_extension', models.CharField(max_length=10)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.DecimalField(decimal_places=90, max_digits=99, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            bases=('drive_data.item',),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drive_data.Item')),
            ],
            bases=('drive_data.item',),
        ),
    ]
