# Generated by Django 3.0.4 on 2020-05-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive_data', '0002_auto_20200421_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileTest',
        ),
    ]
