# Generated by Django 3.0.7 on 2020-06-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive_data', '0002_auto_20200606_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'default_related_name': 'drive_file'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'default_related_name': 'drive_folder'},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_file',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='file',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='drive_file', serialize=False, to='drive_data.Item'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='drive_folder', serialize=False, to='drive_data.Item'),
        ),
    ]
