# Generated by Django 3.0.4 on 2020-03-25 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_data', '0002_auto_20200310_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.DecimalField(decimal_places=90, max_digits=99, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
