# Generated by Django 3.0.3 on 2020-02-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive_data', '0003_auto_20200225_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_Test',
            new_name='FileTest',
        ),
    ]
