# Generated by Django 3.0.4 on 2020-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive_data', '0003_auto_20200313_1750'),
        ('drive_data', '0003_auto_20200325_1149'),
    ]

    operations = [
    ]
