# Generated by Django 3.0.3 on 2020-02-27 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_data', '0004_auto_20200227_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetest',
            name='size',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
