# Generated by Django 3.0.7 on 2020-07-19 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive_data', '0003_auto_20200718_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('permission', models.CharField(choices=[('P', 'Public'), ('S', 'Selective')], default='S', max_length=1)),
                ('access_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive_data.Item')),
            ],
        ),
    ]
