# Generated by Django 3.0.7 on 2020-07-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive_data', '0003_auto_20200718_0843'),
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drive_data.Item'),
        ),
    ]
