# Generated by Django 3.0.7 on 2020-06-09 11:51

import collections
from django.db import migrations, models
import django_fsm
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='GUID')),
                ('state', django_fsm.FSMField(default='initial', max_length=50)),
                ('upload_offset', models.BigIntegerField(default=0)),
                ('upload_length', models.BigIntegerField(default=-1)),
                ('upload_metadata', jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict})),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('temporary_file_path', models.CharField(max_length=4096, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, max_length=255, null=True, upload_to='uploaded')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
